In [1]:
import pygwalker as pyg
import pandas as pd

You can use pygwalker without changing your existing workflow. For example, you can call up Graphic Walker with the dataframe loaded in this way:

In [2]:
df = pd.read_csv("bike_sharing_dc.csv", parse_dates=['date'])
df

,date,month,season,hour,year,holiday,temperature,feeling_temp,humidity,winspeed,casual,registered,count,work yes or not,am or pm,Day of the week
0,2011-01-01,1,winter,0,2011,no,3.28,3.0014,81.0,0.0000,3,13,16,0,am,6
1,2011-01-01,1,winter,1,2011,no,2.34,1.9982,80.0,0.0000,8,32,40,0,am,6
2,2011-01-01,1,winter,2,2011,no,2.34,1.9982,80.0,0.0000,5,27,32,0,am,6
3,2011-01-01,1,winter,3,2011,no,3.28,3.0014,75.0,0.0000,3,10,13,0,am,6
4,2011-01-01,1,winter,4,2011,no,3.28,3.0014,75.0,0.0000,0,1,1,0,am,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,2012-12-31,12,winter,19,2012,no,4.22,1.0016,60.0,11.0014,11,108,119,1,pm,1
17375,2012-12-31,12,winter,20,2012,no,4.22,1.0016,60.0,11.0014,8,81,89,1,pm,1
17376,2012-12-31,12,winter,21,2012,no,4.22,1.0016,60.0,11.0014,7,83,90,1,pm,1
17377,2012-12-31,12,winter,22,2012,no,4.22,1.9982,56.0,8.9981,13,48,61,1,pm,1
17378,2012-12-31,12,winter,23,2012,no,4.22,1.9982,65.0,8.9981,12,37,49,1,pm,1


And then just walk around!

In [3]:
pyg.walk(df)

Box(children=(HTML(value='<div id="ifr-pyg-00061572797bf26bKacyQhmsuErjDMCL" style="height: auto">\n    <head>â€¦

Now you have a Tableau-like user interface to analyze and visualize data by dragging and dropping variables.

Here're some examples:

![](img/1-8ms.gif)

![](img/2-8ms.gif)

[![Manually explore your data with a Tableau-like UI](img/drag-and-drop.gif)](https://docs.kanaries.net/graphic-walker/overview)

## Cool things you can do with Graphic Walker

+ You can change the mark type into others to make different charts, for example, a line chart:

![graphic walker line chart](img/fullscreen-timeseries.png)


+ To compare different measures, you can create a concat view by adding more than one measure into rows/columns.

![graphic walker area chart](img/fullscreen2-timeseries-area.png)

+ To make a facet view of several subviews divided by the value in dimension, put dimensions into rows or columns to make a facets view. The rules are similar to Tableau.

![graphic walker scatter chart](img/fullscreen-scatter-3.png)

+ You can save the data exploration result to a local file.

For more detailed instructions, visit the [Graphic Walker GitHub page](https://github.com/Kanaries/graphic-walker).